### ISSUE TITLE
Diverging "by force" steps in lemmas reduce_to_length_globs and reduce_to_funcs

### ISSUE THREAD

**Issue by mdesharnais** [conrad-watt/wasm-pl-isabelle#2]
After the first `git pull` from the master branch for a long time I noticed that Isabelle diverges when building the formalization. More specifically, `isabelle build -cvD .` times out.

When inspecting with jEdit, I identified the two lemmas `reduce_to_length_globs` and `reduce_to_funcs`, both in `Wasm_Big_Step.thy`, which have `by force` proof steps that seem to diverge.

The problem seems to have been introduced in b131cbc when the axiomatization `host_apply_preserve_store` was changed in `Wasm_Axioms.thy`. I checked if `sledgehammer [timeout = 120]` could find another proof but all provers timed out. I tested with Isabelle 2018, 2019, and 2020.

This strikes me as odd that such a defect would have been unnoticed for so long in the master branch. Is it possible that there is some uncommitted change laying in some local repository?

**Comment by conrad-watt** [comment]
This should be fixed now, sorry! Reopen if you find any issues.
